language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

env:
  global:
  - NODE_ENV=test

before_script:
  - psql -c 'create database wayfarer_test;' -U postgres
  - psql -c "CREATE USER chuksEmma WITH PASSWORD null;" -U postgres
  - npm run build
script:
  - npm run int:test
after_success:
  - npm run coveralls



# language: node_js
# node_js:
#     - "stable"
# script:
#     - npm run int:test
# cache: 
#   directories:
#     - "node_modules"
# addons:
#   apt:
#     update: true    
# services:
#     - postgresql
# before_script:
#     - psql -c 'create database wayfarer_test;' -U postgres
#     - psql -c 'create USER chuksEmma WITH PASSWORD null;' -U postgres
#     - npm run build
# after_success:
#     - npm run coveralls    
# env:
#   global:
#   - NODE_ENV=test
